using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

namespace ScreenScraperFR;

internal class GameInfoFieldsResponse
{
    [JsonPropertyName("infos")]
    public Dictionary<Int32, GameInfoField> Infos { get; set; } = new();
}

[SuppressMessage("ReSharper", "UnusedMember.Global")]
public class GameInfoField
{
    /// <summary>
    /// Numeric ID of the info.
    /// </summary>
    [JsonPropertyName("id")]
    public Int32 Id { get; set; }

    /// <summary>
    /// Short name of the info.
    /// </summary>
    [JsonPropertyName("nomcourt")]
    public required String ShortName { get; set; }

    /// <summary>
    /// Long name of the info.
    /// </summary>
    [JsonPropertyName("nom")]
    public required String Name { get; set; }

    /// <summary>
    /// Category of the info.
    /// </summary>
    [JsonPropertyName("categorie")]
    public required String Category { get; set; }

    /// <summary>
    /// Pipe-separated list of system type IDs where the info is available.
    /// </summary>
    [JsonPropertyName("plateformtypes")]
    public required String PlatformTypes { get; set; }

    /// <summary>
    /// Pipe-separated list of platform IDs where the info is available.
    /// </summary>
    [JsonPropertyName("plateforms")]
    public required String Platforms { get; set; }

    /// <summary>
    /// Type of the info (e.g., varchar, int, groupe, text).
    /// </summary>
    [JsonPropertyName("type")]
    public required String Type { get; set; }

    /// <summary>
    /// Indicates if the info is auto-generated.
    /// </summary>
    [JsonPropertyName("autogen")]
    [JsonConverter(typeof(JsonBooleanConverter))]
    public Boolean IsAutoGenerated { get; set; }

    /// <summary>
    /// Indicates if the info supports multiple regions.
    /// </summary>
    [JsonPropertyName("multiregions")]
    [JsonConverter(typeof(JsonBooleanConverter))]
    public Boolean IsMultiRegion { get; set; }

    /// <summary>
    /// Indicates if the info supports multiple systems.
    /// Note: Can be missing or empty.
    /// </summary>
    [JsonPropertyName("multisupports")]
    [JsonConverter(typeof(JsonBooleanConverter))]
    public Boolean IsMultiSupport { get; set; }

    /// <summary>
    /// Indicates if the info supports multiple versions.
    /// Note: Can be missing or empty.
    /// </summary>
    [JsonPropertyName("multiversions")]
    [JsonConverter(typeof(JsonBooleanConverter))]
    public Boolean IsMultiVersion { get; set; }

    /// <summary>
    /// Indicates if the info supports multiple choices.
    /// </summary>
    [JsonPropertyName("multichoix")]
    [JsonConverter(typeof(JsonBooleanConverter))]
    public Boolean IsMultiChoice { get; set; }
}
